close_when_open = true
force_keyboard_focus = true

[keys.ai]
run_last_response = ["ctrl e"]

[list]
max_entries = 200

[search]
placeholder = " Search..."

[builtins.applications]
launch_prefix = ""
placeholder = " Search apps..."
prioritize_new = true
context_aware = true
show_sub_when_single = false
history = true
icon = ""
hidden = false

[builtins.applications.actions]
enabled = true
hide_category = false

[builtins.bookmarks]
hidden = true

[builtins.calc]
name = "Calculator"
icon = ""
min_chars = 3
prefix = "="
hidden = false

[builtins.windows]
switcher_only = false
hidden = false
icon = ""
name = "Windows"

[builtins.clipboard]
hidden = true

[builtins.commands]
hidden = false
icon = ""
name = "Commands"
placeholder = " Run command..."

[builtins.custom_commands]
hidden = false
icon = "⚡"
name = "Power & System"

[[builtins.custom_commands.commands]]
name = "Lock Screen"
icon = ""
cmd = "hyprlock"

[[builtins.custom_commands.commands]]
name = "Logout"
icon = ""
cmd = "niri msg action quit"

[[builtins.custom_commands.commands]]
name = "Suspend"
icon = "󰒲"
cmd = "systemctl suspend"

[[builtins.custom_commands.commands]]
name = "Reboot"
icon = ""
cmd = "systemctl reboot"

[[builtins.custom_commands.commands]]
name = "Shutdown"
icon = ""
cmd = "systemctl poweroff"

[[builtins.custom_commands.commands]]
name = "Reload Niri"
icon = ""
cmd = "niri msg action reload-config"

[builtins.emojis]
name = "Emojis"
icon = ""
prefix = ":"
hidden = false

[builtins.symbols]
after_copy = ""
hidden = true

[builtins.finder]
use_fd = true
cmd_alt = "xdg-open $(dirname ~/%RESULT%)"
icon = ""
name = "Files"
preview_images = true
hidden = false
prefix = "."
placeholder = " Find files..."

[builtins.runner]
shell_config = ""
switcher_only = false
hidden = false
icon = ""
name = "Run"
placeholder = " Execute..."
prefix = "!"

[builtins.ssh]
hidden = true

[builtins.websearch]
switcher_only = true
hidden = true

[builtins.translation]
hidden = true