return {
  { "folke/tokyonight.nvim", enabled = false },
  { "folke/noice.nvim", enabled = false },
  { "folke/edgy.nvim", enabled = false },
  { "akinsho/bufferline.nvim", enabled = false },
  { "sphamba/smear-cursor.nvim", enabled = false },
  { "echasnovski/mini.animate", enabled = false },
  { "ThePrimeagen/harpoon", enabled = false },
  { "catppuccin/nvim", enabled = false },
  { "nvim-telescope/telescope.nvim", enabled = false },
  { "Exafunction/codeium.nvim", enabled = false },
  { "nvzone/typr", enabled = true },
  { "yetone/avante.nvim", enabled = false },
  { "zbirenbaum/copilot.lua", enabled = false },
  { "github/copilot.nvim", enabled = false },
  { " nvim-neo-tree/neo-tree.nvim", enabled = false },
}
